name: ars_cognitio
description: No more puffed up subscriptions. Connect your cloud keys directly to your phone and move on!
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  googleapis: ^10.1.0
  dart_openai: ^1.9.1
  macos_ui: ^1.12.2
  fluent_ui: ^4.4.2
  fluentui_system_icons: ^1.1.198
  universal_io: ^2.2.0
  fast_log: ^1.0.2
  precision_stopwatch: ^1.0.2
  glitcheffect: ^1.1.1
  hive_flutter: ^1.1.0
  googleapis_auth: ^1.4.0
  http: ^0.13.5
  lzstring: ^2.0.0+2
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  hive: ^2.2.3
  synchronized: ^3.0.1
  path_provider: ^2.0.14
  uuid: ^3.0.7
  flutter_markdown: ^0.6.14
  flutter_chat_ui: ^1.6.6
  foil: ^0.9.0+1
  settings_ui: ^2.0.2
  tinycolor2: ^3.0.1
  dialoger: ^1.0.0
  padded: ^1.0.1
  snackbar: ^1.0.2
  get: ^4.6.5
  file_picker: ^5.2.7
  sliver_tools: ^0.2.9
  toxic: ^1.0.3
  memcached: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
flutter:
  uses-material-design: true
